### ISSUE TITLE
lidar demo

### ISSUE THREAD

**Issue by kentaroy47** [tawnkramer/sdsandbox#16]
@tawnkramer 
I came to your repo looking at the lidar demo but don't see the features enabled in the release.
Looks cool and wanted to try out myself!!
https://www.youtube.com/watch?v=h8kEDzBIr_o

or am I missing something?
do you have an another repo for the lidar feature?

thanks!!

**Comment by kentaroy47** [comment]
oh, I found LiDAR.cs in the repo and got it to work..
thanks!

**Comment by tawnkramer** [comment]
happy you found it. It's in the dev branch for those looking in the future.
