### ISSUE TITLE
 unrecognized arguments: outputs/highway.h5

### ISSUE THREAD

**Issue by jewis123** [tawnkramer/sdsandbox#21]
hello， how to fix this error? 
predict_server.py: error: unrecognized arguments: outputs/highway.h5

the error shows in this way
1. download this repo
2. install the requirements
3. cd sdsandbox
python src/predict_server.py outputs/highway.h5
4. the error shows
![image](https://user-images.githubusercontent.com/23737513/56116229-e6e55380-5f97-11e9-8bb2-2123b7601eb6.png)

**Comment by padalous** [comment]
I have the same error. Tried to look at the file, it's a "Hierarchical Data Format 5 File" (.h5), so tried to read it with pandas :

**Comment by tawnkramer** [comment]
Add a —model= before the model name

**Comment by jewis123** [comment]
wow excellent, it works!  Thx first, and what about the world complexity part ?Does it mean that I should replace the function of gen track to gen world?

**Comment by tawnkramer** [comment]
Just a tiny bit more work than that...

**Comment by jewis123** [comment]
OK ,I see. THX ;)
