### ISSUE TITLE
Several Missing References

### ISSUE THREAD

**Issue by tall-josh** [tawnkramer/sdsandbox#25]
Unity Version: 2017.2.0b11 Personal (64bit)
OS: Ubuntu 18.04

Symptom:
Cannot start any of the driving environments. 
Steps:
1. Play From `Scene --> menu`.
2. Click the "Generated Track" option.

No screen change just stays on `menu` screen and the following errors.

Errors:
![generated_track](https://user-images.githubusercontent.com/18511395/57188652-e2340f80-6f45-11e9-9603-8bde14cf6bc8.png)

If I try the Warehouse track:
![image](https://user-images.githubusercontent.com/18511395/57188662-190a2580-6f46-11e9-9f8e-4002d0e186e9.png)

Upon startup, before running anything I get the following errors.
![startup_warnings](https://user-images.githubusercontent.com/18511395/57188618-fcb9b900-6f44-11e9-94ed-f39736c82c01.png)

Any help would be greatly appreciated. I am currently looking to upgrade my Unity install.

Cheers Josh

**Comment by tall-josh** [comment]
Also, upon opening `Scenes/avc2` and others I notice many missing prefabs. Is there a git-lfs pull or something I'm missing or something?

![image](https://user-images.githubusercontent.com/18511395/57190552-bffabb80-6f5e-11e9-8793-29af718a7796.png)

**Comment by tall-josh** [comment]
Hmmmm, I just checked out the `dev` branch (was on the `donkey`) branch and everything seems to work

**Comment by tleyden** [comment]
@tall-josh I think you want to be on the `donkey` branch.  The `dev` branch is 2 years old.  I'm using the `donkey` branch and have the basics working using Unity 2018.3.14f1.  (OSX 10.12.6)

**Comment by tawnkramer** [comment]
It seems like his Unity version is too old. Please try a 2018 or newer.

The master branch was idle for a long time. I’ve tried to update it a few
weeks ago. Last I checked it was working.

But Mac has presented a special challenge since their awkward stance on
Nvidia drivers and cuda. I’ve mostly given up on it. Dual boot into Linux.
