### ISSUE TITLE
donkey simultor

### ISSUE THREAD

**Issue by Shorouqtalaat** [tawnkramer/sdsandbox#29]
hey 
ruinng this  command 
 python evaluate.py --model=~/mycar/models/example_model.h5
i have this error 
Traceback (most recent call last):
  File "evaluate.py", line 24, in <module>
    from donkey_gym.core.fps import FPSTimer
ModuleNotFoundError: No module named 'donkey_gym'

what can i do ??

**Comment by tawnkramer** [comment]
Is that an old script. I don’t see an evaluate.py. If you are needing steps to follow please check docs.donkeycar.com for a link to donkey gym
