### ISSUE TITLE
Merge conflicts when checking out from `master` to `donkey` branch

### ISSUE THREAD

**Issue by amitection** [tawnkramer/sdsandbox#31]
I was trying to build the simulator on my local machine. According to this documentation https://docs.donkeycar.com/guide/simulator/ I tried to clone the master branch and checkout to the donkey branch and I faced several merge conflicts.

Ofcourse I could simply clone `donkey` branch. But I was just wondering if this intentional that the branches have different source?  Which branch is stable?

**Comment by tawnkramer** [comment]
Do you have steps to reproduce the problem? Afaik they are both stable.
Please let me know the steps and output you are seeing.
