### ISSUE TITLE
Unity won't connect to predict_server.py

### ISSUE THREAD

**Issue by ethanburrell** [tawnkramer/sdsandbox#34]
Hey!

Thank you so much for this amazing project!

I'm trying to connect the predict_server from a a network that I trained. However, when I run predict server, I see "binding to ('0.0.0.0', 9090)" but when I open the unity project and click use "NN steering" nothing happens. 

After I click this in Unity, there is nothing that appears in the terminal. However, when I point a web browser to 127.0.0.1:9090, the terminal prints out "got a new client ('127.0.0.1', 50188)"

Is there some setting that I need to toggle in unity for this to work, or is there a local network problem on my machine?

Thank you!

**Comment by tawnkramer** [comment]
network model changed now.
