### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by huangzhengbin** [tawnkramer/sdsandbox#37]
When I installed requirements, I ran “python predict_server.py --model ../outputs/highway.h5”， and Windows gave me the wrong “ TypeError: __init__() got an unexpected keyword argument 'timestep_limit'”，what should I do?Please help me!

**Comment by tawnkramer** [comment]
Tensorflow 2.0+ probably broke things. Try “pip install tensorflow==1.13.1”
and see if that helps.

**Comment by huangzhengbin** [comment]
I have followed your instruction,but It didn't work,and report the same problem.Then,do you have other suggestions?
