### ISSUE TITLE
Road texture not showing on linux

### ISSUE THREAD

**Issue by araffin** [tawnkramer/sdsandbox#39]
Hello @tawnkramer ,

Building myself the binary or downloading the pre-built one, it seems that there is an issue with the road texture under linux (for level 3 if I remember well):

![Capture d’écran de 2020-04-23 19-56-45](https://user-images.githubusercontent.com/1973948/80132842-96d2a100-859c-11ea-81e1-e380f2707fcb.png)

That does not match what is seen in the doc...
However, no problem with the other levels...
Am i missing something?

My config:
- Ubuntu 18.04

I also tested with a simulation build I did in June 2019, I have the same issue...

**Comment by araffin** [comment]
This issue is not present on windows:

![donkey](https://user-images.githubusercontent.com/1973948/80136308-d18b0800-85a1-11ea-95c9-693b6a5d5385.png)

**Comment by tawnkramer** [comment]
The lack of track indicates there was an error while generating it. The
error was caused by reading a American encoded float into a system
expecting another floating point representation. You can see this by
checking the player log. And this is fixed with the latest sim. Check that
the version says 20.4.9

also, please use the Master branch now.

**Comment by araffin** [comment]
> Check that the version says 20.4.9

How do you check that?
The home screen says "Pandemic edition v20.4"

I used the binary from https://github.com/tawnkramer/gym-donkeycar/releases/tag/v2020.v.9

**Comment by tawnkramer** [comment]
that's the right url.
https://github.com/tawnkramer/gym-donkeycar/releases/download/v2020.v.9/DonkeySimLinux.zip

it should show 20.4.9 on menu screen.

**Comment by araffin** [comment]
Ok, I re-build it from source (I had upgrade unity) and now it's working and I can see the full version, thanks =) (btw, it seems that the linux binary on github may be outdated...

**Comment by araffin** [comment]
I found out why I had the wrong binary: the [documentation](https://docs.donkeycar.com/guide/virtual_race_league/) does not point to the latest release but to the v20.4 (not 20.4.9)

**Comment by tawnkramer** [comment]
Sorry about that. Thanks for the heads up. Will fix those docs.
