### ISSUE TITLE
Unity version warning

### ISSUE THREAD

**Issue by Bleyddyn** [tawnkramer/sdsandbox#9]
When I opened sdsandbox/sdsim in Unity I got this warning:

> Your project was last saved with a different version of Unity.
>   /Users/andrew/Dev/ML/sdsandbox/sdsim
> The saved project (5.6.0xf3Linux) does not match the launched editor (2018.2.0f2)
> This may require re-import. Please be aware that opening in an older version is unsupported.
> Note that if a build target installation is missing, this may also cause a re-import.

After that there was another warning about having to upgrade the project but I forgot to copy the text.

The Unity version is what I downloaded July 10, 2018 from their website for Mac OS X.

**Comment by tawnkramer** [comment]
That's pretty normal when opening older project files with newer versions
of Unity. Let me know if you see any errors when attempting to run.

**Comment by Bleyddyn** [comment]
I haven't tried anything except the basic instructions in the Readme, but it looks like it's working.
